

List<String> getLyrics() {

  return ['Sugar',
  'Sugar',
  'Ooooo ooh',
  'She sits alone, ',
  'waiting for suggestions',
  'Hes so nervous',
    'avoiding all her questions',
  'His lips are dry',
    'her heart is gently pounding',
  'Dont you just know exactly ',
      'what theyre thinking?',
  'If you want my body ',
      'and ya think Im sexy',
  'Come on sugar',
      ' let me know',
  'If you really need me',
      'just reach out and touch me',
  'Come on honey',
      'tell me so',
  'Tell me so baby',

  'Hes acting shy',
      ' looking for an answer',
  'Aw, come on, honey',
      ' lets spend the night together',
  'Now hold on a minute',
      ' before we go much further',
  'Give me a dime so',
      'I can phone my mother',
  'They catch a cab',
      ' to his high rise apartment',
  'At last he can tell',
      'her exactly what his heart meant',

  'If you want my body',
      'and ya think Im sexy',
  'Come on, sugar',
      ' let me know (let me know)',
  'If you really need me',
      'just reach out and touch me',
  'Come on, honey',
      'tell me so (tell me so)',
  'His hearts beating like a drum',
  'Cause at last hes got his girl home',
  'Relax, baby,',
      'now we’re all alone (now we’re all alone)',
  'Come on, sugar',
      ' let me know',

  'If you want my body',
      'and ya think Im sexy',
  'Come on, honey, let me know',
  'If you really need me',
      ' just reach out and touch me',
  'Come on, sugar, let me know',

  'If you want my body',
      'and ya think I’m sexy',
  'Come on, honey',
      ' tell me so',
  'If you really need me',
      ' just reach out and touch me',
  'Come on, sugar',
      ' let me know',

  'Oh, if you want my body',];

}